apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: next
  name: next
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next
  template:
    metadata:
      labels:
        app: next
    spec:
      containers:
      - image: pyaephyohein/next
        imagePullPolicy: Always
        name: next
        ports:
        - containerPort: 80